events {
  worker_connections 1024;
}

http {
  upstream website {
    server website:3000;
  }

  upstream cms_api {
    server cms-backend:4000;
  }

  upstream cms_admin {
    server cms-admin:80;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://cms_api/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /uploads/ {
      proxy_pass http://cms_api/uploads/;
    }

    location /admin/ {
      proxy_pass http://cms_admin/;
    }

    location / {
      proxy_pass http://website;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
